#!/bin/bash
set -x

#socat pty,link=tlay2.pty,raw tcp-listen:1235,reuseaddr,nodelay &
#SOCAT_PID=$!
#sleep 1
qemu-system-i386 -cpu 486 -m 4M -fda build/main/bezbios.img -gdb tcp::1234 -serial tcp:127.0.0.1:1235,server,nodelay $@ &
QEMU_PID=$!
sleep 1
./tlay2_server.py socket://localhost:1235 #tlay2.pty
kill $QEMU_PID #$SOCAT_PID
